Ewelink discover fix and enhancements
GladysAssistant/Gladys pull request #1044
Opened 2021-01-16 14:55 UTC by NickDub

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

2021-02-20 22:02 UTC, atrovato reviewed
Looks fine to me (code only), didn't try in real mode.

I really like the fact you upgrade the eWelink service package version :) 

One question, my device is offline, why can't I add it to Gladys?

![image](https://user-images.githubusercontent.com/1839717/108609656-a2b30d80-73cf-11eb-9cc9-5f9d4db71a71.png)

2021-02-20 22:02 UTC, atrovato commented on server/services/ewelink/lib/device/poll.js
> +//   const response = await connection.getDevicePowerUsage(deviceId);
Commented code is not required.

2021-02-20 22:02 UTC, atrovato commented on server/services/ewelink/lib/device/poll.js
> +        // } else if (feature.type === DEVICE_FEATURE_TYPES.SWITCH.POWER) {
Commented code is not required.

2021-02-20 22:02 UTC, atrovato commented on server/services/ewelink/lib/features/energyPower.js
> +  generateFeature: (channel = 0) => {
Do we really generate power features? Power code looks fully commented.

2021-02-20 22:02 UTC, atrovato commented on server/services/ewelink/lib/features/index.js
> +  //   feature: energyPowerFeature,
Energy commented, commented code is not required.

2021-02-22 18:45 UTC, NickDub commented
> One question, my device is offline, why can't I add it to Gladys?

If the device is offline, we cannot detect the available features and therefore, for the moment, we cannot add it.
In the future, I will add the ability to add and update an unhandled device.

2021-02-22 18:45 UTC, NickDub commented on server/services/ewelink/lib/device/poll.js
> +//   const response = await connection.getDevicePowerUsage(deviceId);
Removed...

2021-02-22 18:45 UTC, NickDub commented on server/services/ewelink/lib/device/poll.js
> +        // } else if (feature.type === DEVICE_FEATURE_TYPES.SWITCH.POWER) {
Removed...

2021-02-22 18:45 UTC, NickDub commented on server/services/ewelink/lib/features/energyPower.js
> +  generateFeature: (channel = 0) => {
Removed...

2021-02-22 18:45 UTC, NickDub commented on server/services/ewelink/lib/features/index.js
> +  //   feature: energyPowerFeature,
Removed...

2021-02-22 20:19 UTC, atrovato approved these changes, later dismissed
Looks good to me, but I don't have any ewelink device anymore, maybe @VonOx have some to test it in real life.

2021-03-01 05:26 UTC, Pierre-Gilles commented
@VonOx could you try this ? :) Looks good to me too, looking for a real world review before merging

2021-03-10 14:43 UTC, atrovato commented
@VonOx do you still have eWelink devices?

2021-03-10 21:16 UTC, VonOx commented
Yes sorry guys for delay, will test this week end.

2021-03-12 16:30 UTC, VonOx commented
Some testing ( With sonoff basic ):

* Account setup OK
* Device discover ok
* Device added to dashboard ok ( but initial state what wrong , displayed on but was off )
* Switch to off , nothing happen ( ok because initial state was wrong )
* Turn on ( OK )
* Turn off ( NOK ) - Displayed off in dashboard but device is on
* After waiting device poll, real state is displayed in dashboard
* Turn off OK

Maybe polling related problem or maybe I'm too fast while testing

2021-03-15 02:30 UTC, Pierre-Gilles commented
> Device added to dashboard ok ( but initial state was wrong , displayed on but was off )
> Switch to off , nothing happen ( ok because initial state was wrong )

So it seems there is an initial state problem? So PR is ok or not ? ^^

2021-04-01 16:48 UTC, NickDub commented
The pr is correct, but there are vulnerabilities.
Can you check it ?

2021-05-23 09:19 UTC, atrovato approved these changes, later dismissed
Ok looks good to me.

2021-05-27 03:50 UTC, Pierre-Gilles requested changes
Hi! Thanks for your PR :) 

I wrote a few very minor changes related to code only. 

On the functional side, was this PR tested properly ?

The bug reported by @VonOx in previous messages were fixed ? 

If it's all good, and it has been tested, I'm good to merge! 🙂

2021-05-27 03:50 UTC, Pierre-Gilles commented on server/services/ewelink/lib/device/index.js
> +      await this.gladys.event.emit(EVENTS.WEBSOCKET.SEND_ALL, {
this.gladys.event.emit is a synchronous function, no need for await

2021-05-27 03:50 UTC, Pierre-Gilles commented on server/services/ewelink/lib/device/index.js
> +        await this.gladys.event.emit(EVENTS.WEBSOCKET.SEND_ALL, {
this.gladys.event.emit is a synchronous function, no need for await

2021-05-27 03:50 UTC, Pierre-Gilles commented on server/services/ewelink/lib/device/discover.js
> +        const deviceInGladys = await this.gladys.stateManager.get(
this.gladys.stateManager.get is a synchronous function, no need for await

2021-06-07 05:55 UTC, Pierre-Gilles commented
Hello! Just saw your changes, looks better! 

On the functional side, was this PR tested properly ?

The bug reported by @VonOx in previous messages were fixed ?

2021-06-07 16:20 UTC, NickDub-old commented
> The bug reported by @VonOx in previous messages were fixed ?

Not yet. I'm trying to reproduce it...
Otherwise, everything is OK.

2021-10-11 03:16 UTC, Pierre-Gilles commented
Hello! Just wanted to know the status of this PR ? :)

If you need help, don't hesitate to ping me on the forum.

2021-10-13 17:50 UTC, NickDub-old commented
I don't have any more ewelink devices to test, but if it's ok for you, this PR is ready to be merged...

2021-10-13 21:51 UTC, VonOx commented
I have one, can test if you need.

2021-10-14 05:06 UTC, Pierre-Gilles commented
OK @VonOx Let me know if the bug you previously saw is indeed fixed :)

2021-10-19 16:00 UTC, VonOx commented
@Pierre-Gilles Not reproduced , so yes it's fixed

2021-10-22 03:29 UTC, Pierre-Gilles commented
Do you confirm that this PR is retro-compatible with existing connected ewelink device ?

There is no breaking change, like users don't need to re-connect their device to make them work ? 

External_id used did not change?

2021-10-22 18:06 UTC, NickDub-old commented
There is no change to the External_id.
This PR is retro-compatible with existing connected ewelink device ;)

2021-10-25 09:29 UTC, Pierre-Gilles approved these changes
Thanks for the PR then! :) 

I'm merging this !

2021-10-25 09:29 UTC, merged