Inject scene variables in other boxes
GladysAssistant/Gladys pull request #1047
Opened 2021-01-18 14:24 UTC by Pierre-Gilles

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

2021-01-18 16:18 UTC, Pierre-Gilles commented
Hi @cicoub13 @VonOx @atrovato, I would love a review from you on this PR! 

This is how it looks like: 

https://user-images.githubusercontent.com/7365207/104939530-d229c100-59b0-11eb-93e1-87bf4c4bcfe1.mp4

Is the shortcut straightforward? (having to type " {{ " to open the variable list ?) Should we use another trigger ? Like "#" ? 

This feature will be extended to basically all input field in scenes, for exemple in the HTTP request it could be super useful to automatically inject a variable into a POST body :)

2021-01-22 21:15 UTC, cicoub13 reviewed
It's ok for me. Tested in multiple conditions 👍 
On little glitch when I decided to change again the user

<img width="389" alt="inject_user_glitch" src="https://user-images.githubusercontent.com/1773153/105547435-c581d180-5cfe-11eb-8c13-54fd98038487.png">

{{ is ok to inject variable.

2021-01-23 08:45 UTC, atrovato requested changes

2021-01-23 08:45 UTC, atrovato commented on front/src/routes/scene/edit-scene/actions/SendMessageParams.jsx
> +              value: `${groupIndex}.${index}.${option.name}`
All these values can be computed once and stored in a const instead of cumputing them n times in the loop.

2021-01-23 08:45 UTC, atrovato commented on front/src/routes/scene/edit-scene/actions/SendMessageParams.jsx
> +      this.tagify.settings.whitelist.length = 0;
Is this empty an array?

2021-01-23 08:45 UTC, atrovato commented on front/src/routes/scene/edit-scene/actions/SendMessageParams.jsx
> +      const textFormatted = this.props.action.text.replaceAll('{{', '[[').replaceAll('}}', ']]');
Can we store `{{` and others in file constants? This will make it easier to change if needed.

2021-01-25 09:09 UTC, Pierre-Gilles commented on front/src/routes/scene/edit-scene/actions/SendMessageParams.jsx
> +              value: `${groupIndex}.${index}.${option.name}`
Variables are changing all the time, so it's not as easy :D  

I tried to cache it the best I could, if you have another idea how we could cache it better..

2021-01-25 09:16 UTC, Pierre-Gilles commented on front/src/routes/scene/edit-scene/actions/SendMessageParams.jsx
> +              value: `${groupIndex}.${index}.${option.name}`
mm I don't follow you

We have: 

- M rows (before this row)
    - Each rows has N boxes 
       - Each box has L variables

We loop on each rows before this one, then on each box in each row, then on each variable in each box.

How could we do better?

2021-01-25 09:25 UTC, Pierre-Gilles commented on front/src/routes/scene/edit-scene/actions/SendMessageParams.jsx
> +      const textFormatted = this.props.action.text.replaceAll('{{', '[[').replaceAll('}}', ']]');
Good idea ! Done.

2021-01-25 09:31 UTC, Pierre-Gilles commented
@cicoub13 zIndex problem fixed! :) Thanks!

2021-01-25 09:46 UTC, merged