WIP: Allows a scene to trigger another scene
GladysAssistant/Gladys pull request #1124
Opened 2021-04-05 14:55 UTC by rob-mccann

### Pull Request check-list

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

### Description of change

This change adds an action to scenes which triggers another scene.

![image](https://user-images.githubusercontent.com/412744/113587814-3f9bd400-9627-11eb-8b41-722465473286.png)

A few assumptions have been made here which I'd be happy to revisit based on feedback:

- There's no validation that a scene exists in the backend
- A scene can only trigger another scene once across all action groups
  - In the cyclical scenario (for example,  Scene A that triggers Scene B that triggers Scene A), each scene will be called once only and a warning message logged. This is handled at execution time by remembers which scenes were already called.
  - There's no cyclical checks/validation done when a scene is created at the moment; I suggest this is handled in a separate PR to make this easier to review and in the interest of making it incrementally better :) 

Closes #797

2021-04-06 07:02 UTC, atrovato reviewed
Tested locally, looks fine.
2 things:
 - we may want to add a message in the UI to tell the user that scenes won't loop
 - execution conditions of the child scene are ignored (to execute it), maybe the user needs to know it too

what about a ℹ️ tooltip on scene selection box?

2021-04-06 07:02 UTC, atrovato commented on server/lib/scene/scene.execute.js
> +    scope.sceneCircularDependencyPreventionList = scope.sceneCircularDependencyPreventionList || new Set();
Hum... I'm not really fan of `sceneCircularDependencyPreventionList` name, a bit long, and is a Set, not a list.
Maybe just `executedScenes`, or `relativeScenes`?

2021-04-06 07:02 UTC, atrovato commented on server/lib/scene/scene.actions.js
> +    if (scope.sceneCircularDependencyPreventionList.has(action.scene)) {
That's nice to check circular execution, but how can we alert user in this case?
Maybe we should add a "warning" message in the scene editor to explain that each depend scenes will be run only once.

2021-04-06 09:40 UTC, rob-mccann commented on server/lib/scene/scene.execute.js
> +    scope.sceneCircularDependencyPreventionList = scope.sceneCircularDependencyPreventionList || new Set();
Naming things is hard 😓 

`scenesAlreadyExecuted` perhaps

2021-04-06 10:23 UTC, Pierre-Gilles commented on server/lib/scene/scene.actions.js
> +    if (scope.sceneCircularDependencyPreventionList.has(action.scene)) {
I think the box in the UI could have a little description explaining that circular execution is prevented ? Just before the select

2021-04-06 10:29 UTC, atrovato commented on server/lib/scene/scene.execute.js
> +    scope.sceneCircularDependencyPreventionList = scope.sceneCircularDependencyPreventionList || new Set();
I know... naming... `alreadyExecutedScenes` instead.

2021-04-06 20:58 UTC, rob-mccann commented on server/lib/scene/scene.execute.js
> +    scope.sceneCircularDependencyPreventionList = scope.sceneCircularDependencyPreventionList || new Set();
done

2021-04-06 20:59 UTC, rob-mccann commented on server/lib/scene/scene.actions.js
> +    if (scope.sceneCircularDependencyPreventionList.has(action.scene)) {
I've added a message - any suggestions for copy and/or 🇫🇷 ?

2021-04-07 06:44 UTC, atrovato commented on server/lib/scene/scene.actions.js
> +    if (scope.sceneCircularDependencyPreventionList.has(action.scene)) {
According to your message `"Scenes will only be called once in a chain, even if they're added multiple times. Trigger conditions will be ignored."`
"Chaque scène ne sera exécutée qu'une seule fois, et les conditions d'exécution seront ignorées."

@Pierre-Gilles ?

2021-04-07 14:00 UTC, Pierre-Gilles commented on server/lib/scene/scene.actions.js
> +    if (scope.sceneCircularDependencyPreventionList.has(action.scene)) {
I would say in french: 

"Les conditions de déclenchements de la scène appelée seront ignorées. Si une scène appelle une autre scène, et vice-versa, Gladys ne tombera pas dans une boucle infinie: chaque scène ne sera exécutée qu'une seule fois. "

2021-04-22 04:22 UTC, Pierre-Gilles requested changes
When I click on the start scene button: 

<img width="1430" alt="Screenshot 2021-04-22 at 12 20 09" src="https://user-images.githubusercontent.com/7365207/115655134-3750d200-a365-11eb-9c47-044f7ae37a9b.png">

I got this error: 

<img width="1158" alt="Screenshot 2021-04-22 at 12 20 30" src="https://user-images.githubusercontent.com/7365207/115655151-420b6700-a365-11eb-809a-9514f8140129.png">

I guess it's because `alreadyExecutedScenes` does not exist at this stage

2021-05-10 04:34 UTC, Pierre-Gilles approved these changes
Looks good to me this time! Thanks for the PR, great work 🙏

2021-05-10 04:35 UTC, merged