Add the ability to vizualize device states on the dashboard
GladysAssistant/Gladys pull request #1248
Opened 2021-07-23 07:34 UTC by Pierre-Gilles

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

2021-09-20 06:02 UTC, VonOx commented
@pierre-gilles Can you provide dataset for testing?

2021-09-20 09:25 UTC, Pierre-Gilles commented
@VonOx I'm not sure if it's the goal, if I share my dataset, you will probably have the same results as I'm having locally: and it works fine on my side.

I want to see with your datasets!

2021-09-20 09:53 UTC, VonOx commented
Ok i will import my production data

2021-09-20 09:56 UTC, VonOx requested changes

2021-09-20 09:56 UTC, VonOx commented on front/src/components/boxs/chart/EditChart.jsx
> +                <Text id="dashboard.boxes.devicesInRoom.editRoomLabel" />
Wrong label here

2021-09-20 09:59 UTC, VonOx commented
Selecting device feature is filling Title box even if a value was already entered

![image](https://user-images.githubusercontent.com/1528694/133984682-2649028b-2a12-4532-b323-35b4995c1ee2.png)

2021-09-24 01:36 UTC, Pierre-Gilles commented
> Selecting device feature is filling Title box even if a value was already entered

Doesn't it make sense to replace the title if the device feature selected changed?

> I can't identify in which room theses values are

You can put the name in the box title: 

<img width="422" alt="Screenshot 2021-09-24 at 09 30 03" src="https://user-images.githubusercontent.com/7365207/134604781-edb525d6-16e3-4c3d-9ed7-b90514ca92ac.png">

<img width="417" alt="Screenshot 2021-09-24 at 09 30 10" src="https://user-images.githubusercontent.com/7365207/134604789-22da7921-a63c-43b9-9870-e89f9f931146.png">

Or maybe you were talking about the default? 

I was fearing putting device name + room name would make it too long by default.

> Relative time problem.
French/English mixed.

Ok, will fix. 

> As a user what I need to do to fix failed aggregation ?

You're right, we need to put somewhere the error message that happened. 

As a user, you won't be able to fix it, but just communicate the bug to us on the forum/Github. 

But I don't expect we'll see some fails, this error happened because it's still WIP, but in production it's like the rest of Gladys, everything is carefully tested and there is no reason it'll fail more than something else :) 

> It would be usefull to combine multiple device feature on the same chart 

Yes, definitely.

> Hability to select a color

Why not indeed, it makes even more sense with multi-devicefeature.

> Display min / max on periode or like this

Yes definitely.

> PS: I will update this comment while testing

Thanks for your test and precious feedback.

I'll spend some time on fixing this and will get back to you! 🙏

2021-09-24 07:59 UTC, Pierre-Gilles commented on front/src/components/boxs/chart/EditChart.jsx
> +                <Text id="dashboard.boxes.devicesInRoom.editRoomLabel" />
Fixed

2021-10-06 17:55 UTC, atrovato reviewed
Not sure all my comments request changes,
I didn't run it, Vonox did ;)
A bit complicated...

2021-10-06 17:55 UTC, atrovato commented on front/src/components/boxs/chart/ApexChartComponent.jsx
> +      options = this.getAreaChartOptions();
This file is kind long, maybe we can extract each case in separated files.

2021-10-06 17:55 UTC, atrovato commented on front/src/components/boxs/chart/EditChart.jsx
> +    this.deviceFeatureBySelector = new Map();
Are you sure you want to use `Map`? Object is not enough?

2021-10-06 17:55 UTC, atrovato commented on front/src/config/i18n/en.json
> +        "editDeviceFeaturesLabel": "Select the device you want to display here.",
Ended with dot, but not other translations, is this expected?
(same on upper line)

2021-10-06 17:55 UTC, atrovato commented on front/src/config/i18n/fr.json
> +        "editNameLabel": "Entrez le nom de cette box.",
Same here for final dot (may be expected).

2021-10-06 17:55 UTC, atrovato commented on server/lib/device/device.calculateAggregate.js
> +        const progress = parseInt(splitted[0], 10);
Looks a bit confused here.
What is the expected `text` value?
If `text = "updateProgress:10:updateProgress"`, what for
`const [,progress] = text.split(':');`

2021-10-06 17:55 UTC, atrovato commented on server/package.json
> +    "test-without-lint": "cross-env NODE_ENV=test ./node_modules/mocha/bin/mocha --recursive ./test/bootstrap.test.js \"./test/**/*.test.js\" --exit",
Cheater! ;)

2021-10-11 02:38 UTC, Pierre-Gilles commented on front/src/components/boxs/chart/ApexChartComponent.jsx
> +      options = this.getAreaChartOptions();
Every function contains the apexchart configuration, maybe I could export this in separate files you're right

2021-10-11 02:44 UTC, Pierre-Gilles commented on front/src/components/boxs/chart/EditChart.jsx
> +    this.deviceFeatureBySelector = new Map();
Yes, I think it's always better to use those objects (Map, Set) when possible instead of using a bare object as a key value store, because Map expose some functions that are designed to work properly and that removes weird bugs.

When using an object, so many times some cases (null/undefined/0) are not well handled.

**Example:** 

```javascript
const myKeyValueStore = {};

keyValueStore['toto'] = 0
```

Later in the code: 

```javascript
if(keyValueStore['toto']) {
    //  0 is considered as "false" in Javascript, so it will not run
}
```

So what's the solution here?

You could do this: 

```javascript
if(keyValueStore['toto'] !== undefined) {
}
```

But then "null" is considered as "not existing" too, so we need to do:


```javascript
if(keyValueStore['toto'] !== undefined || keyValueStore['toto'] !== null) {
}
```

This is starting to become a bit long, and it's hard to grasp what we wanted to do.

Whereas, with a simple map: 

```javascript

const myKeyValueStore = new Map();
myKeyValueStore.set('key', 0);
if(myKeyValueStore.has('key')) {
// we have the guarantee that it handles all cases perfectly.
}
```

2021-10-11 02:45 UTC, Pierre-Gilles commented on front/src/config/i18n/en.json
> +        "editDeviceFeaturesLabel": "Select the device you want to display here.",
Nice catch, fixing

2021-10-11 02:46 UTC, Pierre-Gilles commented on front/src/config/i18n/fr.json
> +        "editNameLabel": "Entrez le nom de cette box.",
Nice catch, fixing.

2021-10-11 02:50 UTC, Pierre-Gilles commented on server/lib/device/device.calculateAggregate.js
> +        const progress = parseInt(splitted[0], 10);
> what for const [,progress] = text.split(':');

No it's not working, because I think we are receiving the data as blob of grouped logs, and sometimes it's grouped with other data.

Example, we can receive: 

```
const text = "SOME DATA RANDOM updateProgress:10:updateProgress OTHER DATA"
```

That's why I substr to remove the beginning of the string, then I split and remove the first part only.

2021-10-11 02:51 UTC, Pierre-Gilles commented on server/package.json
> +    "test-without-lint": "cross-env NODE_ENV=test ./node_modules/mocha/bin/mocha --recursive ./test/bootstrap.test.js \"./test/**/*.test.js\" --exit",
My VSCode already run eslint on save + on paste, so it's really a waste of time to run lint every time I run tests :)

2021-10-14 17:18 UTC, atrovato commented on front/src/components/boxs/chart/ApexChartComponent.jsx
> +      options = this.getAreaChartOptions();
This one is still pending.

2021-10-18 09:29 UTC, Pierre-Gilles commented on front/src/components/boxs/chart/ApexChartComponent.jsx
> +      options = this.getAreaChartOptions();
Done

2021-10-22 05:51 UTC, Pierre-Gilles commented
To me the PR is ready 🚀🙂

I've updated the demo website: 

<img width="1440" alt="Screenshot 2021-10-22 at 12 58 38" src="https://user-images.githubusercontent.com/7365207/138400079-d27912f5-4e85-4a29-87eb-54e82fa13cbb.png">

Let me know if everyone is good to merge this!

2021-10-25 03:08 UTC, merged