Add feature request about camera image rotation 180°
GladysAssistant/Gladys pull request #1297
Opened 2021-09-13 06:51 UTC by VonOx

Add feature request about camera image rotation 180°

2021-09-13 12:18 UTC, VonOx commented
@atrovato @Pierre-Gilles @cicoub13 , if any of you had some times to help me with front.

I'm struggle with switch in ui , I think it's working now because in DB value is updated.

![image](https://user-images.githubusercontent.com/1528694/133082004-14bbefd6-6adf-49dd-b1bc-e328a7304707.png)

Every time I save updated camera, Gladys loop in infinite loading.
![image](https://user-images.githubusercontent.com/1528694/133081737-8d95f61f-7b64-4bb3-944b-0d59da64d9a7.png)

Force refresh and problem is gone.

Where I'm wrong ?

2021-10-11 08:36 UTC, Pierre-Gilles commented
@VonOx Do you still need help with the UI ?

2021-10-11 18:42 UTC, VonOx commented
Yes please

2021-10-11 19:43 UTC, atrovato commented
For your information, demo mode doesn't work here. Parameter is missing in demo.json file.

2021-10-11 19:47 UTC, atrovato commented
And I think here
```
updateCameraRotation = e => {
    let newValue;
    if (e.target.checked) {
      newValue = 1;
      console.log('Je suis actif');
    } else {
      newValue = 0;
      console.log('Je suis inactif');
    }
    this.props.updateCameraRotation(this.props.cameraIndex, newValue);
  };
```
should set string var, not int.
```
updateCameraRotation = e => {
    const newValue = e.target.checked ? '1' : '0';
    this.props.updateCameraRotation(this.props.cameraIndex, newValue);
  };
```

2021-10-12 12:17 UTC, VonOx commented
Thank you @atrovato

But error is still here while saving ( toggle and save works )

![image](https://user-images.githubusercontent.com/1528694/136952151-718e8303-7560-4d10-b360-85f50b49dc1a.png)

Corresponding line :

```js
checked={props.camera.cameraRotation.value === '1'}
```

2021-10-12 18:01 UTC, atrovato commented
There is a bug in `createOrUpdateCamera` and `saveCamera` methods (actions.js).

Device parameters are not mapped as it is in `getRtspCameraDevices` method.
I think we have the problem on "CAMERA_URL" too.

You should reuse this part (please introduce a new method instead of simply copy/paste).
```javascript
const cameraUrlParam = camera.params.find(param => param.name === 'CAMERA_URL');
if (cameraUrlParam) {
  camera.cameraUrl = cameraUrlParam;
}
const cameraRotationParam = camera.params.find(param => param.name === 'CAMERA_ROTATION');
if (cameraRotationParam) {
  camera.cameraRotation = cameraRotationParam;
}
```

2021-10-13 08:35 UTC, VonOx commented
> I think we have the problem on "CAMERA_URL" too.

Without my code , camera save works. It's on me but 🔽 

> Device parameters are not mapped as it is in `getRtspCameraDevices` method.

I don't understand that, I have duplicated the code stuff about `CAMERA_URL` . Is this index related ?

-------------------

![image](https://user-images.githubusercontent.com/1528694/137094563-6c763746-5fe7-499a-83ab-664e3e19329a.png)
cameraRotation => object name is the same as `getRtspCameraDevices`

![image](https://user-images.githubusercontent.com/1528694/137094738-a90cdc47-fab7-4b93-aac1-d5151f245ef8.png)
And this part is for updating value in DB

The difference in `getRtspCameraDevices` is we are getting params by device not by param index ?
I'm right ?

![image](https://user-images.githubusercontent.com/1528694/137096560-2067009e-70ff-4bb2-a204-b9cce55ba61e.png)

2021-10-13 17:38 UTC, atrovato commented
Once we call save WS, we override the camera object, which has no more direct cameraRotation attribute.
But we set it right on load.
The property mapper should be called after we call save WS, before we update state.

That's nice you try yourself, and more, that's nice you ask for help, I appreciate.

2021-10-13 21:01 UTC, VonOx commented
Oh my god I think I got it

saveCamera return the state on newCamera object without param.
```js
async saveCamera(state, index) {
      const camera = state.rtspCameras[index];
      camera.features[0].name = camera.name;
      const newCamera = await state.httpClient.post(`/api/v1/device`, camera);
      const cameraUrlParam = newCamera.params.find(param => param.name === 'CAMERA_URL');
      if (cameraUrlParam) {
        newCamera.cameraUrl = cameraUrlParam;
      }
      const cameraRotationParam = newCamera.params.find(param => param.name === 'CAMERA_ROTATION');
      if (cameraRotationParam) {
        newCamera.cameraRotation = cameraRotationParam;
      }
      const rtspCameras = update(state.rtspCameras, {
        [index]: {
          $set: newCamera
        }
      });
      store.setState({
        rtspCameras
      });
    }
```
This works now, thank you @atrovato

2021-10-14 20:59 UTC, atrovato commented on front/src/routes/integration/all/rtsp-camera/actions.js
> +    async getRstpCameraParams(camera) {
Not sure this should be called `getRstpCameraParams` but maybe `complete` or `map`...

2021-10-14 20:59 UTC, atrovato commented on server/services/rtsp-camera/lib/getImage.js
> +      outputOptions.push('-vf hflip,vflip'); // Rotate 180
Don't we plan to get 90° or only horizontal nor vertical rotation?

2021-10-15 02:40 UTC, Pierre-Gilles commented on server/services/rtsp-camera/lib/getImage.js
> +      outputOptions.push('-vf hflip,vflip'); // Rotate 180
I'm not sure we can even do 90° no ? 

We display only landscape images

2021-10-15 05:28 UTC, VonOx commented on server/services/rtsp-camera/lib/getImage.js
> +      outputOptions.push('-vf hflip,vflip'); // Rotate 180
Not sure about that because most of the camera have a good orientation ( spherical support ) and 90° rotation mean we are loosing aspect ratio. ( weird  things will happen in front )

2021-10-15 05:28 UTC, VonOx commented on front/src/routes/integration/all/rtsp-camera/actions.js
> +    async getRstpCameraParams(camera) {
I'm ok with "complete"

2021-10-16 16:26 UTC, atrovato submitted a review, later dismissed
Good enough to me :)

2021-10-18 05:21 UTC, Pierre-Gilles requested changes
When I start this PR on an existing instance with existing cameras, the UI is broken: 

<img width="653" alt="Screenshot 2021-10-18 at 13 20 02" src="https://user-images.githubusercontent.com/7365207/137673365-d2175879-a04b-490c-a040-9cd61c510f8b.png">

This DEVICE_PARAM should be optional!

2021-10-20 11:11 UTC, VonOx commented
OK, what's the good way to solve this?

2021-10-21 18:28 UTC, atrovato commented
@VonOx you can use `get(props, 'camera.cameraRotation.value') === '1'` instead of `props.camera.cameraRotation.value === '1'`
Using `get` (alread imported) avoid 'undefined' properties.

2021-11-13 09:13 UTC, atrovato submitted a review, later dismissed
Looks fine with `get` usage.

2021-11-13 09:52 UTC, VonOx commented
Not yet, same error throw when saving ( because param not exist and it is not created), trying to figure out on my own 😉

2021-11-13 12:39 UTC, VonOx commented
@atrovato Need some help. I'm trying to create param if not exist in updateCameraRotation function ( mimic addCamera ):

```js
    updateCameraRotation(state, index, value) {
      let cameraRotationParamIndex = state.rtspCameras[index].params.findIndex(
        param => param.name === 'CAMERA_ROTATION'
      );
      if (!cameraRotationParamIndex === null) {
        const rtspCameras = update(state.rtspCameras, {
          [index]: {
            cameraRotation: {
              value: {
                $set: value
              }
            },
            params: {
              [cameraRotationParamIndex]: {
                value: {
                  $set: value
                }
              }
            }
          }
        });
        store.setState({
          rtspCameras
        });
      } else {
        const rtspCameras = update(state.rtspCameras[index], {
          $set: [
            {
              cameraRotation: {
                name: 'CAMERA_ROTATION',
                value: '0'
              },
              params: [
                {
                  name: 'CAMERA_ROTATION',
                  value: '0'
                }
              ]
            }
          ]
        });
        store.setState({
          rtspCameras
        });
      }
    },
```
No api available in front to add param on an existing device ? ( like state.rtspCameras[index].params.add(NAME,VALUE) )
I've tried $push / $set without success.

2021-11-13 13:52 UTC, atrovato commented
Why to you to create param?
Default behavior/value won't do the job?

```javascript
    async complete(camera) {
      const cameraUrlParam = camera.params.find(param => param.name === 'CAMERA_URL');
      /*
      if (cameraUrlParam) {
        camera.cameraUrl = cameraUrlParam;
      }
      */
      camera.cameraUrl = cameraUrlParam || ''; // Not sur for this one

      const cameraRotationParam = camera.params.find(param => param.name === 'CAMERA_ROTATION');
      /* Current state
      if (cameraRotationParam) {
        camera.cameraRotation = cameraRotationParam;
      }
      */
      // New state
      camera.cameraRotation = cameraRotationParam || '0';
      return camera;
    },
```

2021-11-13 14:11 UTC, VonOx commented
Nope I've error in console

![image](https://user-images.githubusercontent.com/1528694/141646956-c8d59e53-91bf-44d7-a614-982c44921a39.png)

Logic error ( I think ) because cameraRotationParamIndex is null ( param doe'snt exist in DB )

```js
    updateCameraRotation(state, index, value) {
      let cameraRotationParamIndex = state.rtspCameras[index].params.findIndex(
        param => param.name === 'CAMERA_ROTATION'
      );
      const rtspCameras = update(state.rtspCameras, {
        [index]: {
          cameraRotation: {
            value: {
              $set: value
            }
          },
          params: {
            [cameraRotationParamIndex]: {
              value: {
                $set: value
              }
            }
          }
        }
      });
```

2021-11-13 16:43 UTC, atrovato commented
Ok, that's only for backward compatibility. Param is missing on already created camera.
So, I think, you should set it up right on load (else part).

```
    async complete(camera) {
      const cameraUrlParam = camera.params.find(param => param.name === 'CAMERA_URL');
      if (cameraUrlParam) {
        camera.cameraUrl = cameraUrlParam;
      }
      const cameraRotationParam = camera.params.find(param => param.name === 'CAMERA_ROTATION');
      if (cameraRotationParam) {
        camera.cameraRotation = cameraRotationParam;
      } else {
        // IF PARAM NOT FOUND, ADD IT
        camera.params.push({ name: 'CAMERA_ROTATION', value: '0' });
      }
      return camera;
    }
```

2021-11-14 08:24 UTC, VonOx commented
Thank you @atrovato , I've understood

2021-11-14 09:53 UTC, atrovato approved these changes
Look great again :)

2022-01-22 08:20 UTC, atrovato commented
This one is ready to merge.

2022-02-18 13:45 UTC, Pierre-Gilles approved these changes
Just tested locally and it works fine, even with legacy devices ! Great work 👏

Sorry for taking so long to review this

2022-02-18 13:56 UTC, merged