Zigbee2mqtt lqi
GladysAssistant/Gladys pull request #1343
Opened 2021-10-30 10:34 UTC by atrovato

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

2022-01-27 19:57 UTC, atrovato commented
I wait for dashboard display...

2022-07-24 12:20 UTC, atrovato commented
It can be insterresting to merge it wirh https://github.com/GladysAssistant/Gladys/pull/1575

2022-09-06 07:35 UTC, VonOx requested changes

2022-09-06 07:35 UTC, VonOx commented on server/services/zigbee2mqtt/exposes/numericType.js
> +    if (expose.name === 'lqi') {
Must be `linkquality`

2022-09-06 07:35 UTC, VonOx commented on server/services/zigbee2mqtt/exposes/numericType.js
> +    lqi: {
Same, must be `linkquality`

2022-09-06 13:50 UTC, VonOx commented
I comment here cause not sure if #1546 is involved

![image](https://user-images.githubusercontent.com/1528694/188604607-b71c0e82-6b2b-476b-b4be-9f73143b9e4b.png)
![image](https://user-images.githubusercontent.com/1528694/188604774-f79198ee-3f71-40ef-afa6-1b1107b715fb.png)

```json
{
          "name": "Signal strength",
          "selector": "zigbee2mqtt-cuisine-signal-integer-linkquality",
          "category": "signal",
          "type": "integer",
          "read_only": true,
          "unit": null,
          "min": 0,
          "max": 255,
          "last_value": 2,
          "last_value_changed": "2022-09-06T13:04:35.969Z"
}
```

![image](https://user-images.githubusercontent.com/1528694/188652311-f7a0a016-8b2f-436c-b44b-e2eed3d3c5ba.png)

2022-09-06 14:15 UTC, VonOx commented
Not sure why my features was created at 255 max.

After manually set to 5 max it's ok in dashboard.

![image](https://user-images.githubusercontent.com/1528694/188658369-9da77b89-a89e-420e-9d3e-5568d2ac5932.png)

2022-09-07 17:40 UTC, atrovato commented on server/services/zigbee2mqtt/exposes/numericType.js
> +    if (expose.name === 'lqi') {
You're right!

2022-09-07 17:40 UTC, atrovato commented on server/services/zigbee2mqtt/exposes/numericType.js
> +    lqi: {
You're right!

2022-09-07 17:41 UTC, atrovato commented
@VonOx max with 255 was an old version.

2022-09-07 18:08 UTC, VonOx approved these changes, later dismissed

2022-09-08 10:11 UTC, Pierre-Gilles commented
Tests are failing on Z2M discover: 

<img width="778" alt="Screenshot 2022-09-08 at 12 10 31" src="https://user-images.githubusercontent.com/7365207/189096448-39dc7607-b6c8-45e9-99e4-cd14158a3447.png">

<img width="754" alt="Screenshot 2022-09-08 at 12 10 36" src="https://user-images.githubusercontent.com/7365207/189096428-a6b9d2d8-66c0-4432-b3ac-04b67289d405.png">

2022-09-08 19:41 UTC, atrovato commented
@VonOx in fact, max=255 is provided by z2m device, I take it from the device if it is provided...
I will need to add a "override" option to force the defined mapping.

2022-09-08 19:45 UTC, VonOx commented
OK that's explain the behavior.

Not sure if it's a good way to store a converted value. ( I know we have already discussed this on forum 😉)

2022-09-12 09:16 UTC, Pierre-Gilles commented
@VonOx Can you retry on your side and confirm when it's working fine? :)

2022-09-12 09:49 UTC, VonOx commented
> @VonOx Can you retry on your side and confirm it's working fine? :)

It is, can be merged.

2022-09-12 13:04 UTC, Pierre-Gilles approved these changes
Good for me, good work 👏

2022-09-12 13:04 UTC, merged