Create sun features
GladysAssistant/Gladys pull request #135
Opened 2016-12-18 18:11 UTC by Jean-PhilippeD

Usefull for sun conditions such as is-it night or is-it day ?

2017-01-27 07:42 UTC, Pierre-Gilles requested changes
Great PR thx ! I'm gonna merge it soon because I need it for the weather module, it's gonna add informations about the current sun status (day/night) 

Just modify the little suggestion I added, and it will be ok :) 

Sorry for the late answer

2017-01-27 07:42 UTC, Pierre-Gilles commented on api/core/sun/index.js
> +module.exports.state = require('./sun.state.js');
Can we just rename the function "state" to "getState" ? :)

2017-01-27 07:42 UTC, Pierre-Gilles commented on api/core/sun/sun.isItNight.js
> +function isItNight(options){
We should add tests to isItNight as well

2017-01-27 07:42 UTC, Pierre-Gilles commented on api/core/sun/sun.isItDay.js
> +function isItDay(options){
We should add tests to isItDay

2017-01-27 22:36 UTC, Jean-PhilippeD commented
I've made the changes you asked for.
You can check, it should be ok

2017-01-28 08:20 UTC, Pierre-Gilles commented
Thx ! I'm merging this !

2017-01-28 08:20 UTC, merged