Device room selector component
GladysAssistant/Gladys pull request #1364
Opened 2021-11-12 18:28 UTC by atrovato

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- ~~[ ] If your changes affects code, did your write the tests?~~
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Next common component: device room selector.

2022-02-22 13:55 UTC, Pierre-Gilles approved these changes

2022-02-22 14:04 UTC, Pierre-Gilles requested changes

2022-02-22 14:04 UTC, Pierre-Gilles commented on front/src/components/device/form/DeviceRoomSelector.jsx
> +@connect('houses,housesGetStatus', actions)
I think there is an issue with the variable name `houses`

As the state is global, it's shared with all other componenents

With have some components that use the same key (`houses`) to store a list of houses without the rooms

It caused some issues in the past, that's why I renamed this key `housesWithRooms` when the room was included

Two ways of fixing this: 

- Rename the key to `housesWithRooms` here
- Stop using global variables (but we are losing the cache)

2022-02-22 14:05 UTC, Pierre-Gilles commented on front/src/components/device/form/DeviceRoomSelector.jsx
> +@connect('houses,housesGetStatus', actions)
Example here : https://github.com/GladysAssistant/Gladys/blob/master/front/src/components/boxs/weather/EditWeatherBox.jsx#L18

2022-02-26 07:29 UTC, atrovato commented on front/src/components/device/form/DeviceRoomSelector.jsx
> +@connect('houses,housesGetStatus', actions)
Nice, thank for this point.
I will rename to `housesWithRooms` and (try to) check all other usages.

2022-05-03 17:56 UTC, atrovato commented
I will take it back and split into multiple smaller PRs, to migration integration pages one by one.
Keep tracking on https://github.com/atrovato/Gladys/pull/40

2022-05-03 17:56 UTC, closed without merging