add purge function on devicestate
GladysAssistant/Gladys pull request #138
Opened 2017-01-27 22:39 UTC by Jean-PhilippeD

I propose to add a "purge" on devicestate using the delete from mysql statement, based on devicetype id and number of days from now you want to keep.

I've added test also, you can check the test and tell me if it is enough.

(Maybe we could think about historize data in a histo table .. ?)

2017-01-28 08:32 UTC, Pierre-Gilles requested changes
Nice PR ! Thanks for this function, this was really needed. 

I underlined a few points, theses are just best coding practice :)

Waiting for you changes and merging this

2017-01-28 08:32 UTC, Pierre-Gilles commented on test/unit/api/core/devicestate/deviceState.purge.test.js
> +           options = {
Be careful, try to use always "var" when you create a variable ! Otherwise, it's kind of global, and it's a bad thing ^^

2017-01-28 08:32 UTC, Pierre-Gilles commented on test/unit/api/core/devicestate/deviceState.purge.test.js
> +           states = {
Same here, use "var" when you create a variable. 

For simple tests like this you can maybe just do : 

```gladys.deviceState.get({devicetype: 1});```

So it's easier to read.

2017-01-28 08:32 UTC, Pierre-Gilles commented on test/unit/api/core/devicestate/deviceState.purge.test.js
> +        }).catch(function(err){
I know I've not always done that in all tests of Gladys, but you can simply do : 

`.catch(done):`

2017-01-28 09:47 UTC, Jean-PhilippeD commented
I've made the change

2017-01-28 10:51 UTC, Jean-PhilippeD commented
I've just tested in on my teleinfo module where I had about 2 millions rows since the beginning of december and I successfully purge data at 15 days :) I'm back at 245k rows.

2017-01-29 08:27 UTC, Pierre-Gilles commented
I'm merging this :)

2017-01-29 08:27 UTC, merged