Update temp/humidity in room #1316
GladysAssistant/Gladys pull request #1465
Opened 2022-03-13 17:58 UTC by atrovato

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- ~~[ ] If your changes affects code, did your write the tests?~~
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- ~~[ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~~
- ~~[ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.~~
- ~~[ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~~
- ~~[ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~~
- ~~[ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).~~

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Update temperature and humdity according to websocket event.

1. Load devices in room
2. Check if event matches device in room
3. If yes, reload data from API

⚠️ I didn't test it in real life

2022-03-15 15:42 UTC, Pierre-Gilles requested changes
I got a little crash on the RoomHumidity component ?

2022-03-15 15:42 UTC, Pierre-Gilles commented on front/src/components/boxs/room-humidity/RoomHumidity.jsx
> +    this.props.session.dispatcher.addListener(WEBSOCKET_MESSAGE_TYPES.DEVICE.NEW_STATE, this.updateRoomHumidity);
session is not defined here it seems

2022-03-15 15:42 UTC, Pierre-Gilles commented on front/src/components/boxs/room-humidity/RoomHumidity.jsx
> +    this.props.session.dispatcher.addListener(WEBSOCKET_MESSAGE_TYPES.DEVICE.NEW_STATE, this.updateRoomHumidity);
<img width="652" alt="Screenshot 2022-03-15 at 15 41 25" src="https://user-images.githubusercontent.com/7365207/158415637-e15e6112-fa51-4fd4-ac85-ce9d5c72c83f.png">

2022-03-16 20:11 UTC, atrovato commented on front/src/components/boxs/room-humidity/RoomHumidity.jsx
> +    this.props.session.dispatcher.addListener(WEBSOCKET_MESSAGE_TYPES.DEVICE.NEW_STATE, this.updateRoomHumidity);
The same on temp box.
Thanks.
Now fixed.

2022-03-18 09:32 UTC, Pierre-Gilles requested changes
I can't get the feature to work, is it working on your side?

2022-03-18 19:38 UTC, atrovato commented
No, that was blind dev, sorry.
I take it back, and will try to emulate it.

2022-04-30 16:23 UTC, atrovato commented
I update this one with Cypress tests.
I used "example" service to fake setValue method. Is it OK for you?

PS: this is based on https://github.com/GladysAssistant/Gladys/pull/1488

2022-05-03 17:50 UTC, atrovato commented
I created cypress tests, with websocket emulation.
I also used the "example" service to store device feature value in database, what do you think about this? @Pierre-Gilles 

For each box, 3 cypress tests:
 1. check empty box
 2. check box well updated with matching feature
 3. check box is not updated with non matching feature


![humidity](https://user-images.githubusercontent.com/1839717/166510310-99400a31-75bf-44c4-b2af-bc81187b7a74.gif)

![temperature](https://user-images.githubusercontent.com/1839717/166510339-ef49189d-ae01-48ad-8555-2e5c0d7b6852.gif)

2022-07-21 09:54 UTC, Pierre-Gilles approved these changes
Tested, works fine, thanks for this PR ! :)

2022-07-21 09:55 UTC, merged