[WIP] Fix CalDAV events sync
GladysAssistant/Gladys pull request #1471
Opened 2022-03-15 21:58 UTC by bertrandda

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Handle full day events without end date (equivalent to 1 day full day event)

Also, if too many changes are requested and `507 Insufficient Storage` status appears, it request again for more (and again while not finished)

2022-03-18 09:01 UTC, Pierre-Gilles requested changes
Thanks for this PR ! :) 

I tried syncing my Google calendar, and it doesn't work anymore (it was working fine before)

```
2022-03-18T08:59:42+0000 <error> calendar.syncUserCalendars.js:72 (Promise.map.concurrency) TypeError: Cannot read property 'props' of undefined
    at CalDAVHandler.requestChanges (/Users/pierregilles/code/gladys/server/services/caldav/lib/calendar/calendar.requests.js:88:59)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.map.concurrency (/Users/pierregilles/code/gladys/server/services/caldav/lib/calendar/calendar.syncUserCalendars.js:70:26)
```

2022-03-18 09:01 UTC, Pierre-Gilles commented on server/services/caldav/lib/calendar/calendar.formaters.js
> +              .format('YYYY-MM-DDTHH:mm:ss'),
Is this really the expected behavior ? In your experience, the "start" will be at 00:00 in this case ?

Just to be sure it'll work with scenes, if it's a full day event, we need the event to be from 00:00 to 00:00 (Or 23:59 )

2022-04-01 14:46 UTC, Pierre-Gilles commented
Waiting for this before merging: https://community.gladysassistant.com/t/gladys-4-service-caldav/5838/79?u=pierre-gilles

2022-04-03 19:19 UTC, bertrandda commented
Last commit fix #1494

2022-04-04 10:24 UTC, merged