Scenes - decimals in the "continue only if" block
GladysAssistant/Gladys pull request #1683
Opened 2023-01-09 15:32 UTC by VonOx

FIX #1585

2023-01-10 18:47 UTC, atrovato requested changes
Some comments here 😉

2023-01-10 18:47 UTC, atrovato commented on front/src/routes/scene/edit-scene/actions/only-continue-if/Condition.jsx
> +      newValue = Number.parseFloat(e.target.value);
I think you can use `parseFloat` for both integer and float.
I get the same result for integer with `Number.parseFloat(12)`

2023-01-10 18:47 UTC, atrovato commented on front/src/routes/scene/edit-scene/actions/only-continue-if/Condition.jsx
> +    if (Number.isInteger(newValue)) {
`newValue` is undefined here!

2023-01-10 18:47 UTC, atrovato commented on front/src/routes/scene/edit-scene/actions/only-continue-if/Condition.jsx
> +      newValue = Number.parseFloat(e.target.value);
For more, 
`Number.parseFloat("ab") === NaN` but `Number.parseFloat("1ab") === 1`

I think we'll need a `/^\d+(\.\d+)?$/` regex to check that we only have numbers.

2023-01-10 20:02 UTC, VonOx commented
> Some comments here 😉

Thank you Alex, I will make the change.

I have also changed the event to onBlur ( lost focus) because on change with actual if statement prevent decimal input (dot). With only parsefloat I can revert to onChange, I don't know what is the best.

2023-01-11 07:23 UTC, VonOx commented on front/src/routes/scene/edit-scene/actions/only-continue-if/Condition.jsx
> +      newValue = Number.parseFloat(e.target.value);
Input type number do the job

2023-01-11 19:27 UTC, atrovato commented
onBlur forces the user to leave the field for updates to be taken into account.
So if the user uses "enter" key on keyboard without leaving the field, changes on the filed will be avoid.

2023-01-13 08:09 UTC, VonOx commented
@atrovato I've tested with "enter key" and focus is not lost and even if I hit save button on scene, new value is handled.
onBlur is working great here.

2023-01-13 18:16 UTC, atrovato commented
Do I understand everything is alright?

2023-01-13 18:30 UTC, VonOx commented
> Do I understand everything is alright?

With onBlur => Yes

2023-01-13 19:28 UTC, atrovato approved these changes
Ok :)

2023-01-16 03:32 UTC, Pierre-Gilles requested changes
EDIT: Deleting my previous message, it works!! Issue on my side :)

2023-01-16 03:36 UTC, Pierre-Gilles approved these changes
Good for me, it works fine in the UI and it works fine with a real device / real scene! 

Thanks for this PR 🙏 

PS: forget my previous review, I messed up my test ^^

2023-01-20 04:40 UTC, merged