Initial commit
GladysAssistant/Gladys pull request #1768
Opened 2023-05-01 19:01 UTC by rpochet

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [x ] Is the linter passing? (`npm run eslint` on both front/server)
- [ x] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

In scene, provide selection of device feature instance of device in 'Turn ON/OFF light/switch' actions.

![image](https://user-images.githubusercontent.com/5940493/235510659-d97e4514-7820-4f13-aa56-1a62e8cb2203.png)

Before:
![image](https://user-images.githubusercontent.com/5940493/235511185-5d2df40e-a7fa-41ee-9f1e-26295be1013d.png)

New proposal:
![image](https://user-images.githubusercontent.com/5940493/235510549-21d2199c-9e94-4d68-9f98-7d23f0d26a21.png)

2023-05-05 04:39 UTC, Pierre-Gilles requested changes
Thanks for the PR, it works fine on my side ! great work 👏 

You need to write a DB migration to update all existing scenes, otherwise all the scene already working will stop working for existing Gladys users.

I wrote other feedbacks in the code.

2023-05-05 04:39 UTC, Pierre-Gilles commented on front/src/routes/scene/edit-scene/actions/TurnOnOffLightParams.jsx
> +          label: deviceFeature.name
I agree with being able to select the feature in this scene action, but the deviceFeature.name is not necessarily good in all cases. 

Some integrations like Philips Hue never exposes the deviceFeature.name so the user doesn't even know it exists.

A mixed approach like we do on other scene actions with `getDeviceFeatureName` function would be better no ? 

Example: https://github.com/GladysAssistant/Gladys/blob/1222d3f9f1c687a1f7e30328abdef86b0c8bf1a4/front/src/routes/scene/edit-scene/actions/DeviceGetValueParams.jsx#L33

2023-05-05 04:39 UTC, Pierre-Gilles commented on server/lib/scene/scene.actions.js
> -      } catch (e) {
Why removes all the catch ? the goal of the catch here was:

- If a light doesn't respond, we still want to shut down the other lamps, it's weird to stop the scene for this?

2023-05-05 15:45 UTC, rpochet commented
> You need to write a DB migration to update all existing scenes, otherwise all the scene already working will stop working for existing Gladys users.

How can I test DB migration?

2023-05-08 08:11 UTC, Pierre-Gilles commented
@rpochet Currently we don't have any ways to unit test data migration

I bet you could write a unit test importing a migration file and then calling the up function if you want to ? :)

2023-05-08 08:11 UTC, Pierre-Gilles commented
@rpochet Currently we don't have any ways to unit test data migration

I bet you could write a unit test importing a migration file and then calling the up function if you want to ? :)

2023-05-08 08:12 UTC, Pierre-Gilles commented
@rpochet Currently we don't have any ways to unit test data migration

I bet you could write a unit test importing a migration file and then calling the up function if you want to ? :)

2023-12-01 09:00 UTC, closed without merging