MELCloud integration (Mitsubishi Electric devices)
GladysAssistant/Gladys pull request #1839
Opened 2023-08-01 12:32 UTC by callemand

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to [the community](https://community.gladysassistant.com/) for testing before merging.
- [x] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

The goal of this PR is to add communication between MELCloud and Gladys to be able to control air conditioning provide by Mitsubishi
For the moment only  air conditioning is available but we can add Air-To-Water and Energy-Recovery-Ventilation devices later.
<img width="363" alt="Screenshot 2023-08-01 at 14 30 51" src="https://github.com/GladysAssistant/Gladys/assets/11317212/67c95ad1-b201-4848-bb7b-34d894489fbc">

<img width="1244" alt="Screenshot 2023-08-01 at 14 31 19" src="https://github.com/GladysAssistant/Gladys/assets/11317212/0b22f2c8-6c5d-4fcc-b771-a50d6bda97ec">

<img width="404" alt="Screenshot 2023-08-01 at 14 31 59" src="https://github.com/GladysAssistant/Gladys/assets/11317212/4515e855-e328-4bce-84c5-ef12663b67fd">
<img width="1205" alt="Screenshot 2023-08-01 at 14 31 36" src="https://github.com/GladysAssistant/Gladys/assets/11317212/d07b1e8a-6618-4569-8952-f1c26d2cfc3a">
<img width="1240" alt="Screenshot 2023-08-01 at 14 31 32" src="https://github.com/GladysAssistant/Gladys/assets/11317212/998c78b5-f6fe-45f5-843e-db946bcb05ad">

2023-09-08 12:38 UTC, Pierre-Gilles requested changes
A few feedbacks! 

Be careful, there are a lot of references to the Tuya integration (variable names, file name, ..)

But otherwise, nothing serious, looks like a really good PR 😎

2023-09-08 12:38 UTC, Pierre-Gilles commented on server/test/services/melcloud/lib/controllers/tuya.controller.test.js
> +const sinon = require('sinon');
tuya.controller?

2023-09-08 12:38 UTC, Pierre-Gilles commented on server/services/melcloud/index.js
> +    timeout: 1000,
1s timeout is a bit extreme no? on ADSL, could be easily reached. 5000 feels more safe :)

2023-09-08 12:38 UTC, Pierre-Gilles commented on front/src/routes/integration/all/melcloud/device-page/DeviceTab.jsx
> +      const tuyaDevices = await this.props.httpClient.get('/api/v1/service/melcloud/device', options);
tuya?

2023-09-08 12:38 UTC, Pierre-Gilles commented on front/src/routes/integration/all/melcloud/device-page/DeviceTab.jsx
> +  render({}, { orderDir, search, getTuyaStatus, tuyaDevices, housesWithRooms }) {
tuya

2023-09-28 08:52 UTC, Pierre-Gilles requested changes
Great PR 👏 
I have found just a tiny console.log remaining in the front, but nothing serious :) 

Otherwise, it's good for me!

2023-09-28 08:52 UTC, Pierre-Gilles commented on front/src/routes/integration/all/melcloud/setup-page/SetupTab.jsx
> +      console.log('melCloudPassword', melCloudPassword);
console.log

2023-09-28 08:58 UTC, callemand commented on front/src/routes/integration/all/melcloud/setup-page/SetupTab.jsx
> +      console.log('melCloudPassword', melCloudPassword);
Fixed

2023-09-28 09:14 UTC, merged