Zigbee2mqtt add missing exposes owon pir313 e
GladysAssistant/Gladys pull request #1962
Opened 2023-12-01 22:25 UTC by William-De71

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to the community ([french forum](https://community.gladysassistant.com/)/[english forum](https://en-community.gladysassistant.com/)) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Add tamper and battery low expose in zigbee2mqtt integration

![image](https://github.com/GladysAssistant/Gladys/assets/11477113/73d36efd-6a72-4dcb-aa47-7a8d3eb53337)

2023-12-07 13:09 UTC, Pierre-Gilles requested changes
Thanks for the PR! :)

2023-12-07 13:09 UTC, Pierre-Gilles commented on server/services/zigbee2mqtt/exposes/binaryType.js
> +      type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
Same feedback as the other PR, do it makes sense to categorize the feature as a battery feature, where it's not?

Imagine we have a device that have a feature "battery_high": true/false, how do we handle those features?

I think we need another category for this type of sensor

BATTERY_LOW seems good!

2023-12-07 22:22 UTC, William-De71 commented on server/services/zigbee2mqtt/exposes/binaryType.js
> +      type: DEVICE_FEATURE_TYPES.SENSOR.BINARY,
You are right, modification done!

2023-12-08 08:51 UTC, Pierre-Gilles approved these changes
Looks good to me! Tested locally, thanks for the PR :)

2023-12-08 08:52 UTC, merged