feat: Add doc link on each integration + style consistency
GladysAssistant/Gladys pull request #1969
Opened 2023-12-07 15:30 UTC by jbrisavoine

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [x] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to the community ([french forum](https://community.gladysassistant.com/)/[english forum](https://en-community.gladysassistant.com/)) for testing before merging.
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Following the request [https://community.gladysassistant.com/t/rendre-les-menus-homogene/8581/1](url):

- Add documentation link on each integration pages.
- Change icons and style for consistency
- Update `src/components/documentation/DeviceConfigurationLink.jsx` to be able to chose the path of the documentation

Before:
<img width="931" alt="2023 12 07_PR_BEFORE" src="https://github.com/GladysAssistant/Gladys/assets/138247436/15d0e725-6f1f-4f5a-9fc0-b0a48762a9c4">

After:
<img width="941" alt="2023 12 07_PR_AFTER" src="https://github.com/GladysAssistant/Gladys/assets/138247436/ed223cca-dfb8-49bb-a442-70ee84c53b78">

2023-12-08 09:01 UTC, Pierre-Gilles requested changes
Great PR ! I have a few feedbacks on the included files in this PR, but nothing really serious :) 

For the Camera integration, it seems a bit too compact since the change, could we increase the width of each camera box ?

![Screenshot 2023-12-08 at 09 57 25](https://github.com/GladysAssistant/Gladys/assets/7365207/2f44301c-2c5e-4b6e-a7d9-b650053e188a)

Maybe we can put 2 cameras per row now?

2023-12-08 09:01 UTC, Pierre-Gilles commented on front/cypress/cypress.config.js
> +  component: {
I'm not sure this is related to the current PR, if you want to modify the Cypress config, can you do it in a separate PR ? :)

2023-12-08 09:01 UTC, Pierre-Gilles commented on front/cypress/support/component-index.html
> +  <head>
same

2023-12-08 09:01 UTC, Pierre-Gilles commented on front/cypress/support/component.js
> +// require('./commands')
same

2023-12-08 09:01 UTC, Pierre-Gilles commented on front/package.json
> +    "commonjs": "^0.0.1",
Doesn't seem related to the current PR

2023-12-08 10:15 UTC, jbrisavoine commented on front/cypress/cypress.config.js
> +  component: {
Sorry, it's my mistake. No need for the PR

2023-12-08 10:15 UTC, jbrisavoine commented on front/cypress/support/component-index.html
> +  <head>
Same

2023-12-08 10:16 UTC, jbrisavoine commented on front/cypress/support/component.js
> +// require('./commands')
Same

2023-12-08 10:16 UTC, jbrisavoine commented on front/package.json
> +    "commonjs": "^0.0.1",
same same...

2023-12-08 10:29 UTC, jbrisavoine commented
Fix size of camera box
<img width="907" alt="2023 12 08_PR_FIX" src="https://github.com/GladysAssistant/Gladys/assets/138247436/435c89c3-55f7-4f82-ae0a-9ab91de51217">

2023-12-08 12:43 UTC, Pierre-Gilles requested changes
Nice PR! :)

2023-12-08 12:43 UTC, Pierre-Gilles commented on front/src/routes/integration/all/nextcloud-talk/NextcloudTalk.jsx
> +                    documentKey="nextcloudTalk"
This doesn't link to any documentation ! 

Maybe, let's put "nextcloud-talk" as the key and add a new documentation on the website?

2023-12-08 12:43 UTC, Pierre-Gilles commented on front/src/routes/integration/all/openai/Layout.jsx
> +                    documentKey="openai"
This doesn't link to any documentation!

2023-12-11 15:08 UTC, Pierre-Gilles commented on front/src/routes/integration/all/openai/Layout.jsx
> +                    documentKey="openai"
Fixed

2023-12-15 09:21 UTC, Pierre-Gilles commented on front/src/routes/integration/all/nextcloud-talk/NextcloudTalk.jsx
> +                    documentKey="nextcloudTalk"
Both documentation are live!

2023-12-15 09:22 UTC, merged

2023-12-15 09:23 UTC, Pierre-Gilles commented
@all-contributors please add jbrisavoine for code