[Zwavejs UI] Binary Switch support
GladysAssistant/Gladys pull request #2002
Opened 2024-01-14 12:06 UTC by sescandell

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [x] If your changes affects code, did your write the tests?
- [x] Are tests passing? (`npm test` on both front/server)
- [x] Is the linter passing? (`npm run eslint` on both front/server)
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] ~If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)~
- [x] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to the community ([french forum](https://community.gladysassistant.com/)/[english forum](https://en-community.gladysassistant.com/)) for testing before merging.
- [ ] ~If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)~
- [ ] ~If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).~
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.js`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Binary Switch support tested with real life device Fibaro Wall plug - FGWPE-102.

Manage displaying state and updating state from the UI. Also working with scenes (when the current implemented door sensor opens, it turns on the Binary Switch)

![image](https://github.com/GladysAssistant/Gladys/assets/1559970/12ad0c0a-b3fb-411d-9b76-e890e4e040dc)

![image](https://github.com/GladysAssistant/Gladys/assets/1559970/1952aa7d-40fa-4391-ba80-e5d84549457e)

![image](https://github.com/GladysAssistant/Gladys/assets/1559970/1b2885e8-475c-4c8e-88db-14196a8a1081)

2024-01-26 08:41 UTC, Pierre-Gilles requested changes
Hey! Thanks for your PR :) 

I tried your PR with the only device I have (Fibaro door opening sensor), and I have this error in the logs: 

```
2024-01-26T09:36:33+0100 <error> index.js:15 (process.<anonymous>) unhandledRejection catched: Promise {
  <rejected> NotFoundError: DeviceFeature zwavejs-ui:2-113-0-access_control-door_state_simple not found
      at DeviceManager.newStateEvent (/Users/pierregilles/code/gladys/server/lib/device/device.newStateEvent.js:17:11)
      at EventEmitter.emit (node:events:517:28)
      at Event.emit (/Users/pierregilles/code/gladys/server/lib/event/index.js:18:16)
      at ZwaveJSUIHandler.onNodeValueUpdated (/Users/pierregilles/code/gladys/server/services/zwavejs-ui/lib/zwaveJSUI.onNodeValueUpdated.js:38:5)
```

It seems you're modifying the external_id format

Isn't the current format enough?

It was: 

```
zwavejs-ui:2:0:notification:access_control:door_state_simple
```

In my case

2024-01-26 08:41 UTC, Pierre-Gilles commented on server/services/usb/package.json
> +    "serialport": "^12.0.0"
Not sure if it's the right PR to upgrade serialport?

2024-01-26 08:41 UTC, Pierre-Gilles commented on server/services/usb/index.js
> +  const { SerialPort } = require('serialport');
Could it be done in a separate PR? It's easier to review/rollback

2024-01-26 08:41 UTC, Pierre-Gilles commented on server/test/services/usb/index.test.js
> +  serialport: { SerialPort: SerialPortMock },
Same

2024-01-28 17:45 UTC, sescandell commented
> It seems you're modifying the external_id format
> 
> Isn't the current format enough?
> 
> It was:
> 
> ```
> zwavejs-ui:2:0:notification:access_control:door_state_simple
> ```
> 
> In my case

I've gone back and forth on this so much that I don't really know anymore. Let me check: either I tell you, or I rollback.

2024-01-28 18:45 UTC, sescandell commented
@Pierre-Gilles I rolled back the feature external id format. It should be the same as before.

I reverted serialport too.

2024-02-02 10:38 UTC, Pierre-Gilles commented
@sescandell Thanks ! I restarted the tests !

2024-02-02 10:45 UTC, Pierre-Gilles requested changes

2024-02-02 10:45 UTC, Pierre-Gilles commented on server/services/usb/package-lock.json
>        }
still some serial port code here

2024-02-09 10:06 UTC, Pierre-Gilles approved these changes
Amazing work !! 👏

Tested locally on my side, it works fine with my Fibaro Door Opening sensor.

Can you make a PR to update the documentation and tell that we are now supporting binary switches ? ( https://github.com/GladysAssistant/v4-website ) 

In french: https://gladysassistant.com/fr/docs/integrations/zwavejs-ui/
And in english: https://gladysassistant.com/docs/integrations/zwavejs-ui/

Thanks 🙏

2024-02-12 13:31 UTC, merged