Fix Broken Function Level Authorization & Sensitive Data Exposure Vulnerabilities
GladysAssistant/Gladys pull request #2158
Opened 2024-11-05 21:50 UTC by bnematzadeh

### Description
While reviewing the code, I encountered two vulnerabilities: one is the lack of access to call the /v1/user endpoint, and the other is the disclosure of sensitive user information, such as their encrypted passwords, etc. In `user.controller.js`, there is a function defined as `getUsers`, and according to the following code in `routes.js`, we see that it is possible to call this endpoint through a user who is simply logged into the system:
```
'get /api/v1/user': {
authenticated: true,
controller: userController.getUsers,
}
```
In `getUsers`, various parameters can be received through the query string. I came across an interesting parameter named `fields`, which allows us to set multiple values using commas in the query string and send them. The value of `fields `is stored in the `queryParams `variable within the get function and is included in the query. The problem here is that, unlike other application routes that remove the password and other sensitive fields before sending the response, there is no such code in this case to prevent this, and we can read sensitive user fields from the server. 
For the proof of concept, I wrote a security test. Before running it, ensure that the request is sent from a user who is not an admin. 
![test](https://github.com/user-attachments/assets/38b25af9-ec55-43eb-a1f1-4d5040f147ce)

2024-11-06 07:32 UTC, Pierre-Gilles requested changes
Thanks for this PR 🙏
I wrote 2 small comments on the unit test 🙂

2024-11-06 07:32 UTC, Pierre-Gilles commented on server/test/security/user.test.js
> +        console.log(res.body)
Can you remove this log and add an "expect" statement to check that no password is returned?

2024-11-06 07:32 UTC, Pierre-Gilles commented on server/test/security/user.test.js
> +  it('should return all users with password - regular user', async () => {
The title should be "should return all users without password"

2024-11-08 07:19 UTC, Pierre-Gilles requested changes
It seems you forgot to run prettier

2024-11-08 07:19 UTC, Pierre-Gilles commented on server/test/security/user.test.js
> +        expect(res.body).to.not.have.key('password')
I don't think this work as res.body is a list.

You should probably do:

```
 res.body.forEach((user) => {
    expect(user).to.not.have.property('password');
  });
```

2024-11-08 13:03 UTC, Pierre-Gilles commented
@bnematzadeh There is an issue with eslint in your file, let me know if you need help fixing it

2024-11-08 13:50 UTC, bnematzadeh commented
> @bnematzadeh There is an issue with eslint in your file, let me know if you need help fixing it

Prettier was run on this code before the commit, but I don’t know what the issue is. Can you help me?

2024-11-08 13:52 UTC, Pierre-Gilles commented
![Screenshot 2024-11-08 at 14 52 06](https://github.com/user-attachments/assets/6724a255-452a-45d4-85c6-b6774add5cac)

2024-11-08 14:54 UTC, Pierre-Gilles approved these changes
Looks good to me! Thanks for this PR! :)

2024-11-08 14:54 UTC, merged