feat(scenes): Add does not contain for Calendar action
GladysAssistant/Gladys pull request #2187
Opened 2024-12-17 09:51 UTC by cicoub13

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [X] If your changes affects code, did your write the tests?
- [X] Are tests passing? (`npm test` on both front/server)
- [X] Is the linter passing? (`npm run eslint` on both front/server)
- [X] Did you run prettier? (`npm run prettier` on both front/server)
- [X] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [X] Did you test this pull request in real life? With real devices? If this development is a big feature or a new service, we recommend that you provide a Docker image to the community ([french forum](https://community.gladysassistant.com/)/[english forum](https://en-community.gladysassistant.com/)) for testing before merging.

### Description of change

Provides a "does not contain" in "continue only if calendar event" action

![image](https://github.com/user-attachments/assets/95f71cd7-3fd8-4993-ae93-86a5b37a2ae4)

⚠️ If multiple events are happening now and at least one does not contain the word, scene will continue.

2025-01-20 10:23 UTC, Pierre-Gilles commented
@cicoub13 FYI: https://community.gladysassistant.com/t/liste-deroulante-dune-condition-incomplete/9238/7?u=pierre-gilles

2025-01-27 16:45 UTC, Pierre-Gilles requested changes

2025-01-27 16:45 UTC, Pierre-Gilles commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +    case 'does-not-contains':
Why didn't you do the opposite of contains?

```
queryParams.where.name = {
        [Op.notLike]: `%${calendarEventName}%`,
      };
```

2025-01-27 16:47 UTC, cicoub13 commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +    case 'does-not-contains':
It was my first implementation, but the case where we have two events with:
- event 1 with calendarEventName in name
- event 2 without calendarEventName in name
will continue the scene (because at least one event 2 found) and it's not what we want.

2025-01-27 16:49 UTC, Pierre-Gilles commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +    case 'does-not-contains':
Oh yes indeed, you're right 🫣

2025-01-27 16:55 UTC, Pierre-Gilles requested changes

2025-01-27 16:55 UTC, Pierre-Gilles commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +    // If at least an event is found not containing the word, we want to stop the scene
The comment is not related, we are in the function to calendar.findCurrentlyRunningEvent

2025-01-27 16:55 UTC, Pierre-Gilles commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +      return [];
I'm not sure of the implementation

this function is supposed to return event matching a condition

Here you are doing the job of the scene it seems, or am I wrong?

2025-01-27 17:21 UTC, cicoub13 commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +      return [];
You are right. But the calendar events returned by this function are not sufficient to implement the does not contain in the scene code. I will move this part in the scene.actions.js
Do I need to create a new function or tweak this one?

2025-01-27 17:25 UTC, Pierre-Gilles commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +      return [];
No you can just tweak this function, but this function should do what's advertised: find events matching a condition. If this function was used at other places, it should work as well :) 

> I will move this part in the scene.actions.js

Yes!

2025-01-28 09:55 UTC, cicoub13 commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +    // If at least an event is found not containing the word, we want to stop the scene
Moved to `server/lib/scene/scene.actions.js`

2025-01-28 09:55 UTC, cicoub13 commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +      return [];
Moved to `server/lib/scene/scene.actions.js`

2025-01-28 18:34 UTC, Pierre-Gilles requested changes

2025-01-28 18:34 UTC, Pierre-Gilles commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +    case 'does-not-contains':
Still not sure why this function does the same thing for 'has-any-name' and 'does-not-contains' 

On peut parler en français si c'est plus simple pour toi pour expliquer :)

2025-01-28 18:36 UTC, Pierre-Gilles commented on server/lib/calendar/calendar.findCurrentlyRunningEvent.js
> +    case 'does-not-contains':
Pour moi, la fonction findCurrentlyRunningEvent est indépendante des scènes, et doit donc avoir un comportement logique même si on oublie toute la partie scène

Hors là ce n'est pas le cas

2025-01-31 09:10 UTC, Pierre-Gilles requested changes

2025-01-31 09:10 UTC, Pierre-Gilles commented on server/lib/scene/scene.actions.js
> +      // if at least one event is found containing the word, we want to stop the scene (so events stays empty)
> we want to stop the scene (so events stays empty)

Depends on what the user has chosen no?

2025-01-31 09:10 UTC, Pierre-Gilles commented on front/src/routes/scene/edit-scene/actions/CalendarIsEventRunning.jsx
> +                </option>
As this new mode is quite tricky to understand, I would add a small paragraph below it that's displayed only when the option is selected to explain exactly what's this mode is doing

2025-04-10 00:46 UTC, closed without merging