documentation for the functions time
GladysAssistant/Gladys pull request #354
Opened 2018-05-14 17:48 UTC by pjap93

- time.isItPM.js
- time.isItNight.js
- time.isItEvening.js
- time.isItAM.js

2018-05-23 20:23 UTC, Pierre-Gilles requested changes
Thanks for your PR ! I have a one request for changes, and will merge it just after :)

2018-05-23 20:23 UTC, Pierre-Gilles commented on api/core/time/time.isItAM.js
> +          if(result.state === 'morning') return Promise.resolve(true);
Here, switching to Promise.resolve is not mandatory because you're already in a promise so a promise is already returned!

2018-05-24 20:29 UTC, pjap93 commented on api/core/time/time.isItAM.js
> +          if(result.state === 'morning') return Promise.resolve(true);
it's done too !!

2018-07-21 09:13 UTC, pjap93 commented
salut,
j'ai bien fais les modifications que tu m'avais demandé mais j'arrive pas a valider le changement !!! impossible de modifier "Changes requested".

2018-07-21 19:07 UTC, merged