✨ add device Philips Hue LWA001
GladysAssistant/Gladys pull request #853
Opened 2020-08-20 12:00 UTC by guillaumeLamanda

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?  
  Tests don't pass on my computer before my development. Anyway, the test seems to do the job for my dev.
- [ ] Are tests passing? (`npm test` on both front/server). 
  Nope :  
<details>
  <summary>Tests logs</summary>
  <br/>
  ```
➜  gladys git:(fix/851) ✗ y test
yarn run v1.22.0
$ run-p test-server test-front
$ cd front && npm test
$ cd server && npm test
npm WARN lifecycle The node binary used for scripts is /var/folders/x2/7l4632kj22zbd10qrmt_4p8c0000gn/T/yarn--1597924271393-0.9069599397111185/node but npm is using /Users/guillaumelamanda/.nvm/versions/node/v14.6.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> gladys-front@ test /Users/guillaumelamanda/lab/gladys/front
> jest --coverage

npm WARN lifecycle The node binary used for scripts is /var/folders/x2/7l4632kj22zbd10qrmt_4p8c0000gn/T/yarn--1597924271395-0.22046470681559027/node but npm is using /Users/guillaumelamanda/.nvm/versions/node/v14.6.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> gladys-server@ pretest /Users/guillaumelamanda/lab/gladys/server
> npm run eslint

npm WARN lifecycle The node binary used for scripts is /var/folders/x2/7l4632kj22zbd10qrmt_4p8c0000gn/T/yarn--1597924271395-0.22046470681559027/node but npm is using /Users/guillaumelamanda/.nvm/versions/node/v14.6.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> gladys-server@ eslint /Users/guillaumelamanda/lab/gladys/server
> eslint .

 RUNS  tests/header.test.js

/Users/guillaumelamanda/lab/gladys/server/services/usb/api/usb.controller.js
  13:17  warning  Unexpected unnamed function  func-names

/Users/guillaumelamanda/lab/gladys/server/services/zwave/index.js
  7:25  error  Unable to resolve path to module 'openzwave-shared'  import/no-unresolved

/Users/guillaumelamanda/lab/gladys/server/test/benchmark/triggers.js
  61:8  warning  Unexpected constant condition  no-constant-condition

/Users/guillaumelamanda/lab/gladys/server/test/lib/gateway/GladysGatewayClientMock.test.js
  4:33  warning  Unexpected unnamed function  func-names

✖ 4 problems (1 error, 3 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gladys-server@ eslint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gladys-server@ eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/guillaumelamanda/.npm/_logs/2020-08-20T11_51_17_726Z-debug.log
npm ERR! Test failed.  See above for more details.
 FAIL  tests/header.test.jsxit code 1.
  Initial Test of the Header
    ✕ Header renders Gladys Assistant title and 8 items in header (3ms)
    ✕ Should return null, login page doesnt need a header
    ✕ [Backslash URL] Header renders Gladys Assistant title and 8 items in header (1ms)
    ✕ [Backslash URL] Should return null, login page doesnt need a header

  ● Initial Test of the Header › Header renders Gladys Assistant title and 8 items in header

    TypeError: this.contextRender is not a function
      
      at RenderContext.render (node_modules/preact-render-spy/src/preact-render-spy.js:462:10)
      at deep (node_modules/preact-render-spy/src/preact-render-spy.js:472:76)
      at shallow (node_modules/preact-render-spy/src/preact-render-spy.js:473:25)
      at Object.<anonymous> (tests/header.test.js:25:253)
          at new Promise (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  ● Initial Test of the Header › Should return null, login page doesnt need a header

    TypeError: this.contextRender is not a function
      
      at RenderContext.render (node_modules/preact-render-spy/src/preact-render-spy.js:462:10)
      at deep (node_modules/preact-render-spy/src/preact-render-spy.js:472:76)
      at shallow (node_modules/preact-render-spy/src/preact-render-spy.js:473:25)
      at Object.<anonymous> (tests/header.test.js:25:498)
          at new Promise (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  ● Initial Test of the Header › [Backslash URL] Header renders Gladys Assistant title and 8 items in header

    TypeError: this.contextRender is not a function
      
      at RenderContext.render (node_modules/preact-render-spy/src/preact-render-spy.js:462:10)
      at deep (node_modules/preact-render-spy/src/preact-render-spy.js:472:76)
      at shallow (node_modules/preact-render-spy/src/preact-render-spy.js:473:25)
      at Object.<anonymous> (tests/header.test.js:25:675)
          at new Promise (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  ● Initial Test of the Header › [Backslash URL] Should return null, login page doesnt need a header

    TypeError: this.contextRender is not a function
      
      at RenderContext.render (node_modules/preact-render-spy/src/preact-render-spy.js:462:10)
      at deep (node_modules/preact-render-spy/src/preact-render-spy.js:472:76)
      at shallow (node_modules/preact-render-spy/src/preact-render-spy.js:473:25)
      at Object.<anonymous> (tests/header.test.js:25:937)
          at new Promise (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

Test Suites: 1 failed, 1 total
Tests:       4 failed, 4 total
Snapshots:   0 total
Time:        1.986s
Ran all test suites.
ERROR: "test-server" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```
</details>

- [ ] Is the linter passing? (`npm run eslint` on both front/server)
  Nope, see logs 👆
- [x] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

This pull request adds the compatibility for the Philips Hue LWA001

2020-08-20 12:06 UTC, guillaumeLamanda commented
That if the lint phases was done in the CI ?  
I also think prettier should be a pre-commit hook (`husky` + `lint-staged`).

2020-08-20 15:55 UTC, Pierre-Gilles commented
Thanks for your first PR ! 🚀

**About the linting**

I recommend using an IDE (like VS Code) with the Prettier + Eslint extension installed + “Format on save”/“Format on paste” parameter activated. With that, your code will be formatted and linted each type you save a file.

Example:

<img width="614" alt="Screenshot 2020-08-20 at 17 50 13" src="https://user-images.githubusercontent.com/7365207/90795003-d40e2c00-e30d-11ea-8705-25f0e0054d88.png">

**About pre-commit hooks**

I’m not really in favor of pre-commit hooks in general (even pre-push hooks). 

With pre-commit hooks, committing is slower and not working consistently (when prettier returns an error for example).

Git should be as fast as possible, so that developers can commit as much as they wants. We want to incentivize a rich git history and frequents commits so developers can go back to their previous code as much as possible, and avoid data loss in case of broken/stolen/lost laptop. 

It can sound paranoid for a one file PR like this one, but many big PRs on Gladys can be worked on for months, so we want to incentivize developers to commit as frequently as possible, even if prettier/eslint is not passing. 

**About linting on CI**

About the linting on CI, I’m not in favor of it either. I think linting is for the developer, it helps the developer see what’s wrong in his code visually (you should have linting displayed live in your IDE), so he can improve and understand his mistakes. 

As [this article](https://www.thoughtworks.com/insights/blog/pre-commit-don-t-git-hooked) says it nicely

“Ironically, The discipline of maintaining a stable build is gained through the experience of breaking the build.”

**Running tests**

About the tests, as you modified the backend only, I recommend that your run only the backend tests suites locally. 

Go to the `server` folder, and run `npm test`.

Here, your didn’t write the tests for your service so the coverage is going down and coverage check is failing.

You need to modify the server/test/services/philips-hue/lights.json file and add the JSON of the light you just added. 

It’ll make sure that your light is well handled now, and that it keeps working in the future. 

See this changes in the PR #781 https://github.com/GladysAssistant/Gladys/pull/781/files#diff-ba109fc7d8fc8cc0fdab8d523fa70749

2020-08-21 12:19 UTC, guillaumeLamanda commented
Ok, I understand the main point. That's ok for me, every project has his own rules, and I'm ok to use those ones.  

About running tests, I was not able to run them due to errors with the node module version. I can't find any package specifying a version for the project. Did I miss something? 

Anyway, the contribution should be good by now

2020-08-21 15:53 UTC, Pierre-Gilles commented
> About running tests, I was not able to run them due to errors with the node module version. I can't find any package specifying a version for the project. Did I miss something?

I suppose you mean “Node version”, we use Node LTS (Node 12).

Without more logs it’s hard to help. Don’t hesitate to create a specific post on our forum if you want help on this.

About your changes, you didn’t put the correct informations in the JSON, see the other rows in the file.

2020-08-23 09:45 UTC, guillaumeLamanda commented
> I suppose you mean “Node version”, we use Node LTS (Node 12).  

Yes, that's the part I missed. I was using node 14, and the tests don't run with this version.  
Just a thought: maybe specifying the node version could help future developers?  
It can be specified under the `engine` key in `package.json`, or `nvm` is a common solution to do so.  
What do you think?

> About your changes, you didn’t put the correct informations in the JSON, see the other rows in the file.

Indeed, I didn't pay enough attention to the JSON structure. Change done ✅

2020-08-24 08:50 UTC, Pierre-Gilles requested changes
>Just a thought: maybe specifying the node version could help future developers?

Good idea, I added the Node version used in the documentation for now! 

> It can be specified under the engine key in package.json, or nvm is a common solution to do so.
What do you think?

Good idea for the engine key :) 

So I just reviewed your code, and it seems your PR is breaking the LOM002 integration. If you have a close look at the switch case, the LOM002 used to return an ON/OFF plug device, and now it returns a Philips Hue white light.

Can you fix this?

<img width="782" alt="Screenshot 2020-08-24 at 10 42 06" src="https://user-images.githubusercontent.com/7365207/91023414-cea72f00-e5f6-11ea-877b-f3cbd5fce512.png">

It makes me think that tests are not strict enough because this should have been caught in tests. 

Before we improve philips hue tests, can you fix your code + add a comment on the ` case 'LWA001':`l line because when another developer will read this file, he won't understand what is a "LWA001" and can make the same mistake as you :) 

By the way, the `getPhilipsHueWhiteLight` line is now two times in the file and it should be there only once.

<img width="938" alt="Screenshot 2020-08-24 at 10 49 19" src="https://user-images.githubusercontent.com/7365207/91023995-90f6d600-e5f7-11ea-9073-badc7bdeb7d5.png">

You should put your case statement before the first getPhilipsHueWhiteLight()

2020-08-24 09:38 UTC, guillaumeLamanda commented
> Good idea, I added the Node version used in the documentation for now!
> Good idea for the engine key :)

Awesome! 

> So I just reviewed your code, and it seems your PR is breaking the LOM002 integration. If you have a close look at the switch case, the LOM002 used to return an ON/OFF plug device, and now it returns a Philips Hue white light.
> 
> Can you fix this?

Indeed. It is corrected by now. 😄 

> It makes me think that tests are not strict enough because this should have been caught in tests.

When I looked at the test case, it seems ok IMO. But maybe the controller should be handled by another file dedicated to controllers? It is a bit strange to have controllers in a file called `lights` 🤔 

Another thought: I have seen Ikea light in this folder called `philips-hue`. Did they work the same way?

2020-08-24 12:05 UTC, Pierre-Gilles commented
Thanks for fixing, it's way better now.

> When I looked at the test case, it seems ok IMO. B

What I meant, is that our tests should verify that the expected light object are the expected one, right now we don't really verify in tests, thus validating your PR despite it being broken.

 > But maybe the controller should be handled by another file dedicated to controllers? It is a bit strange to have controllers in a file called lights 🤔

The `lights.json` file is just a fixture file used for mocking in the `mocks.test.js` file. 

The tests code is in files like this one: https://github.com/GladysAssistant/Gladys/blob/master/server/test/services/philips-hue/light/light.getLights.test.js

> Another thought: I have seen Ikea light in this folder called philips-hue. Did they work the same way?

Yes, IKEA lights are philips hue compatible and handled in the Philips Hue service the same way

2020-08-24 12:07 UTC, merged

2020-08-24 12:09 UTC, Pierre-Gilles commented
@all-contributors please add @guillaumeLamanda for code