Update questions.fr.json
GladysAssistant/Gladys pull request #962
Opened 2020-11-18 08:38 UTC by tlse-vins

Suggestion d'ajout de phrases pour l'instant en français, je peux en rajouter au fur et a mesure.

### Pull Request check-list

To ensure your Pull Request can be accepted as fast as possible, make sure to review and check all of these items:

- [ ] If your changes affects code, did your write the tests?
- [ ] Are tests passing? (`npm test` on both front/server)
- [ ] Is the linter passing? (`npm run eslint` on both front/server)
- [ ] Did you run prettier? (`npm run prettier` on both front/server)
- [ ] If you are adding a new features/services, did you run integration comparator? (`npm run compare-translations` on front)
- [ ] If your changes modify the API (REST or Node.js), did you modify the API documentation? (Documentation is based on comments in code)
- [ ] If you are adding a new features/services which needs explanation, did you modify the user documentation? See [the GitHub repo](https://github.com/GladysAssistant/v4-website) and the [website](https://gladysassistant.com).
- [ ] Did you add fake requests data for the demo mode (`front/src/config/demo.json`) so that the demo website is working without a backend? (if needed) See [https://demo.gladysassistant.com](https://demo.gladysassistant.com).

NOTE: these things are not required to open a PR and can be done afterwards / while the PR is open.

### Description of change

Please provide a description of the change here. It's always best with screenshots, so don't hesitate to add some!

2020-11-20 13:55 UTC, Pierre-Gilles requested changes
It seems you didn't format your PR with prettier, so the build is failing.

See my comments for other changes :)

2020-11-20 13:55 UTC, Pierre-Gilles commented on server/config/brain/chat/questions.fr.json
> +    "questions": ["Gladys raconnte moi une blague.", "Gladys est ce que tu connais une blague?","raconte moi une blague."],
typo "raconnte"

2020-11-20 13:55 UTC, Pierre-Gilles commented on server/config/brain/chat/questions.fr.json
> +    "answers": ["J'en connais plein, mais je ne suis pas sûre que tu les comprennent!","On ne dit pas enrichi, mais Henry va satisfaire un besoin naturel.","Tu connais la blague du diable? Dommage el
Pou la blague #1: "J'en connais plein, mais je ne suis pas sûre que tu les comprennent!" J'ai peur que l'utilisateur réponde "vas y quand même", ou un autre truc, et le problème c'est que Gladys saura pas répondre à ça. Il faut vraiment essayer de prendre des blagues qui n'incite pas à répondre :) 

Pour la blague "enrichi", je suis moyen chaud, ça fait pas très sérieux, j'aurais plus vu des trucs plus grand public, genre: 

- L’autre jour, j’ai raconté une blague à mes vêtements. Ils étaient pliés.
- Qui s’occupe de la décoration à l’Elysée ? Le ministère de l’intérieur.

2020-11-20 13:55 UTC, Pierre-Gilles commented on server/config/brain/chat/questions.fr.json
> +    "answers": ["Hey, je suis votre assistante domotique!","Bonjour, je suis votre assistante domotique","Salut, je suis votre assistante domotique!"]
Typo, en français il y a un espace avant un point d'exclamation

2020-11-20 13:55 UTC, Pierre-Gilles commented on server/config/brain/chat/questions.fr.json
> +    "answers": ["Hey!","Salut","Bonjour, je suis Gladys."]
Je remarque qu'il y avait une typo dans le text original, il y a un espace avant un point d'exclamation en français

2020-11-20 14:16 UTC, tlse-vins commented
Ok, je comprend.
C'était un premier test, j'attendais ton retour.
Je vais faire plus attention sur la typo avec les espaces et les fautes de frappes.
Pour les blagues, ok je comprends, j'ai pris les 2 premières que j'ai trouvé.

Dans l'idée, est ce que je peux rajouter des phrases, et des tournures pour enrichir le chat?
C'est une des choses que je peux faire car je ne connais pas le codage.

Pour les labels utilisés, existe il un fichier où je peux les retrouver tous par rapport aux différents services?

2020-11-20 15:14 UTC, Pierre-Gilles commented
Dans l'idée, tu peux carrément enrichir la base de phrase c'est clairement un truc utile ! 

Toutes les clés utilisées sont dans le dossier "brain" que tu as déjà édité. Tu peux regarder toutes les conversations possibles et enrichir à souhait.

2020-11-23 08:23 UTC, Pierre-Gilles commented
Pense à faire tourner eslint/prettier avant de pousser tes modifications :)

2020-11-23 10:28 UTC, Pierre-Gilles commented
Il faut que tu sois sur d'avoir un environnement de développement local fonctionnel.

Tutoriel dans la documentation: https://gladysassistant.com/fr/docs/api/setup-development-environnement

Suis la partie "backend", tu n'as modifié que le backend ici.

Ensuite, pour faire tourner Eslint, tu te mets dans le dossier `server` sur ta machine, et tu exécute la commande: 

```
npm run eslint
```

Pour faire tourner Prettier, tu te mets sur le dossier `server` aussi, et tu fais: 

```
npm run prettier
```

2020-11-25 15:25 UTC, VonOx commented
I close this PR

I teach @tlse-vins how to work with git/github and setup dev env in windows ( this will serve as base for incoming documentation )

2020-11-25 15:25 UTC, closed without merging